# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54e099ac66fda52df37263034e5be5dce66c3199cb04ad6a5b667a3ec10b0c80426d65fcd0b069dc093e59edddbd113808dc0ef31d30a0eb20a43a60ebd64125

test:
  secret_key_base: 4f6ebddd6c14f2c00d84015735c2254a6898938800424912080b1365341fe0ec2f4d291d1b8240b6a34919333dc0a88a369e7d14fb21e1206cdedb49775fc128

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
